# Generated by Django 3.2.5 on 2021-11-08 17:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=1000)),
                ('phone_number', models.DecimalField(decimal_places=0, max_digits=14)),
                ('shipping_cost', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('type_product', models.CharField(choices=[('women', '1'), ('men', '2'), ('bag', '3'), ('shoes', '4'), ('watches', '5')], default='1', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('district', models.CharField(choices=[('Quận 1', '1'), ('Quận 2', '2'), ('Quận 3', '3'), ('Quận 4', '4'), ('Quận 5', '5'), ('Quận 6', '6'), ('Quận 7', '7'), ('Quận 8', '8'), ('Quận 9', '9'), ('Quận 10', '10'), ('Quận 11', '11'), ('Quận 12', '12'), ('Quận Bình Tân', '13'), ('Quận Bình Thạnh', '14'), ('Quận Gò Vấp', '15'), ('Quận Phú Nhuận', '16'), ('Quận Tân Bình', '17'), ('Quận Tân Phú', '18'), ('Thành Phố Thủ Đức', '19'), ('Huyện Bình Chánh', '20'), ('Huyện Cần Giờ', '21'), ('Huyện Củ Chi', '22'), ('Huyện Hóc Môn', '23'), ('Huyện Nhà Bè', '24')], default='1', max_length=50, primary_key=True, serialize=False)),
                ('shipping_cost', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product_attr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(default='red', max_length=100)),
                ('stock', models.IntegerField(default=0)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('product_image', models.CharField(max_length=100)),
                ('product_slug', models.CharField(max_length=10, null=True)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('product_attr', models.TextField(max_length=500, null=True)),
                ('count', models.IntegerField(default=1)),
                ('order', models.CharField(max_length=8, null=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
            ],
        ),
        migrations.AddConstraint(
            model_name='product_attr',
            constraint=models.UniqueConstraint(fields=('product_id', 'attribute'), name='unq_prod'),
        ),
    ]
