# Generated by Django 3.2.5 on 2021-11-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_slug',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
