# Generated by Django 3.2.5 on 2021-10-30 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product_attr_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='product_attr',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
