# Generated by Django 3.2.5 on 2021-11-13 20:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='price',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product_image',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product_slug',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.date(2021, 11, 14)),
        ),
    ]
