# Generated by Django 3.2.5 on 2021-10-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20211030_1255'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product_attr',
            name='unq_prod',
        ),
        migrations.RemoveField(
            model_name='product_attr',
            name='data',
        ),
        migrations.AlterField(
            model_name='product_attr',
            name='attribute',
            field=models.CharField(default='red', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='product_attr',
            constraint=models.UniqueConstraint(fields=('product_id', 'attribute'), name='unq_prod'),
        ),
    ]
