# Generated by Django 3.2.5 on 2021-11-13 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20211114_0352'),
    ]

    operations = [
        migrations.CreateModel(
            name='XImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extensive_img', models.CharField(max_length=100, unique=True)),
                ('main_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
            ],
        ),
    ]
