# Generated by Django 3.2.5 on 2021-11-13 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_ximages'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='addition_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
