# Generated by Django 3.2.5 on 2021-11-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20211107_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=1000)),
                ('phone_number', models.DecimalField(decimal_places=0, max_digits=14)),
            ],
        ),
    ]
